sudo: false
language: node_js
branches:
    only:
        - master
    exclude:
        - test
notifications:
  email: false
node_js:
  - 6
script:
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
