sudo: false
language: node_js
branches:
    only:
        - master
    exclude:
        - test
notifications:
  email: false
node_js:
  - 6
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run done
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
